name: Build and deploy ASP.Net Core app to Azure Web App - PDC-Ai-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build with dotnet
        run: dotnet build backend/WebApp.Api/WebApp.Api.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish backend/WebApp.Api/WebApp.Api.csproj -c Release -o "${{ github.workspace }}/publish"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_36B5700EF2774602ACF59386A2E9481A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2CACA7B093954DD08D8FA0073470F6B1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCF3375069C543FDB2DF214EBEBCE6F2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: PDC-Ai-App
          package: ./publish
